import { TransactionType } from "@/types/transaction";

export const data = [
  {
    id: 25,
    date: "2025-06-01",
    description: "Épargne projet",
    category: "Épargne",
    type: TransactionType.SAVING,
    debit: 500,
    credit: 0,
  },
  {
    id: 24,
    date: "2025-05-20",
    description: "Achat matériel sport",
    category: "Loisirs",
    type: TransactionType.EXPENSE,
    debit: 90,
    credit: 0,
  },
  {
    id: 23,
    date: "2025-05-15",
    description: "Salaire mensuel",
    category: "Travail",
    type: TransactionType.INCOME,
    debit: 0,
    credit: 2500,
  },
  {
    id: 22,
    date: "2025-05-10",
    description: "Restaurant",
    category: "Sorties",
    type: TransactionType.EXPENSE,
    debit: 60,
    credit: 0,
  },
  {
    id: 21,
    date: "2025-05-05",
    description: "Remboursement ami",
    category: "Divers",
    type: TransactionType.INCOME,
    debit: 0,
    credit: 50,
  },
  {
    id: 20,
    date: "2025-05-01",
    description: "Assurance voiture",
    category: "Transport",
    type: TransactionType.EXPENSE,
    debit: 130,
    credit: 0,
  },
  {
    id: 19,
    date: "2025-04-20",
    description: "Épargne vacances",
    category: "Épargne",
    type: TransactionType.SAVING,
    debit: 200,
    credit: 0,
  },
  {
    id: 18,
    date: "2025-04-15",
    description: "Salaire mensuel",
    category: "Travail",
    type: TransactionType.INCOME,
    debit: 0,
    credit: 2500,
  },
  {
    id: 17,
    date: "2025-04-09",
    description: "Achat livres",
    category: "Éducation",
    type: TransactionType.EXPENSE,
    debit: 35,
    credit: 0,
  },
  {
    id: 16,
    date: "2025-04-05",
    description: "Vente objet d'occasion",
    category: "Divers",
    type: TransactionType.INCOME,
    debit: 0,
    credit: 100,
  },
  {
    id: 15,
    date: "2025-04-01",
    description: "Facture internet",
    category: "Services",
    type: TransactionType.EXPENSE,
    debit: 50,
    credit: 0,
  },
  {
    id: 14,
    date: "2025-03-20",
    description: "Achat cadeau",
    category: "Cadeaux",
    type: TransactionType.EXPENSE,
    debit: 80,
    credit: 0,
  },
  {
    id: 13,
    date: "2025-03-15",
    description: "Salaire mensuel",
    category: "Travail",
    type: TransactionType.INCOME,
    debit: 0,
    credit: 2500,
  },
  {
    id: 12,
    date: "2025-03-10",
    description: "Remboursement prêt",
    category: "Dettes",
    type: TransactionType.EXPENSE,
    debit: 200,
    credit: 0,
  },
  {
    id: 11,
    date: "2025-03-05",
    description: "Réparation voiture",
    category: "Transport",
    type: TransactionType.EXPENSE,
    debit: 250,
    credit: 0,
  },
  {
    id: 10,
    date: "2025-03-01",
    description: "Épargne trimestrielle",
    category: "Épargne",
    type: TransactionType.SAVING,
    debit: 400,
    credit: 0,
  },
  {
    id: 9,
    date: "2025-02-20",
    description: "Achat vêtements",
    category: "Habillement",
    type: TransactionType.EXPENSE,
    debit: 150,
    credit: 0,
  },
  {
    id: 8,
    date: "2025-02-15",
    description: "Salaire mensuel",
    category: "Travail",
    type: TransactionType.INCOME,
    debit: 0,
    credit: 2500,
  },
  {
    id: 7,
    date: "2025-02-10",
    description: "Abonnement streaming",
    category: "Divertissement",
    type: TransactionType.EXPENSE,
    debit: 15,
    credit: 0,
  },
  {
    id: 6,
    date: "2025-02-05",
    description: "Prime exceptionnelle",
    category: "Travail",
    type: TransactionType.INCOME,
    debit: 0,
    credit: 500,
  },
  {
    id: 5,
    date: "2025-02-01",
    description: "Facture électricité",
    category: "Services",
    type: TransactionType.EXPENSE,
    debit: 120,
    credit: 0,
  },
  {
    id: 4,
    date: "2025-01-25",
    description: "Épargne mensuelle",
    category: "Épargne",
    type: TransactionType.SAVING,
    debit: 300,
    credit: 0,
  },
  {
    id: 3,
    date: "2025-01-20",
    description: "Loyer",
    category: "Logement",
    type: TransactionType.EXPENSE,
    debit: 900,
    credit: 0,
  },
  {
    id: 2,
    date: "2025-01-16",
    description: "Achat épicerie",
    category: "Alimentation",
    type: TransactionType.EXPENSE,
    debit: 75,
    credit: 0,
  },
  {
    id: 1,
    date: "2025-01-15",
    description: "Salaire mensuel",
    category: "Travail",
    type: TransactionType.INCOME,
    debit: 0,
    credit: 2500,
  },
];
